language: cpp
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq quilt libqtwebkit-dev qconf libqca2-dev libxss-dev libaspell-dev zlib1g-dev libsm-dev libotr2-dev libtidy-dev
script: ./travis.sh

